"""initial schema

Revision ID: 97642b24c238
Revises: 
Create Date: 2026-06-28 00:24:56.525066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97642b24c238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('classe', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('descricao_curta', sa.String(length=255), nullable=True),
    sa.Column('descricao_completa', sa.Text(), nullable=True),
    sa.Column('status_sistema', sa.String(length=30), nullable=False),
    sa.Column('status_regulatorio', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produto_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('fonte', sa.String(length=255), nullable=True),
    sa.Column('status_validacao', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('moeda', sa.String(length=8), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('data_coleta', sa.String(length=40), nullable=True),
    sa.Column('fonte', sa.String(length=255), nullable=True),
    sa.Column('status_validacao', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('grupo_quimico', sa.String(length=120), nullable=True),
    sa.Column('composicao', sa.Text(), nullable=True),
    sa.Column('nutrientes_principais', sa.Text(), nullable=True),
    sa.Column('culturas_comuns', sa.Text(), nullable=True),
    sa.Column('alvos_controle', sa.Text(), nullable=True),
    sa.Column('uso_principal', sa.String(length=120), nullable=True),
    sa.Column('modo_aplicacao', sa.String(length=120), nullable=True),
    sa.Column('tipo_liberacao', sa.String(length=40), nullable=True),
    sa.Column('fonte_tecnica', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('area_total_ha', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('variedade', sa.String(length=120), nullable=True),
    sa.Column('safra', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.String(length=40), nullable=True),
    sa.Column('data_fim', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('funcao', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financeiro_lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gleba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('poligono_geojson', sa.Text(), nullable=True),
    sa.Column('tipo_solo', sa.String(length=80), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ia_interacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_arquivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultura_gleba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultura_id', sa.Integer(), nullable=False),
    sa.Column('gleba_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.String(length=40), nullable=True),
    sa.Column('data_fim', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cultura_id'], ['cultura.id'], ),
    sa.ForeignKeyConstraint(['gleba_id'], ['gleba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplicacao_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultura_gleba_id', sa.Integer(), nullable=False),
    sa.Column('produto_base_id', sa.Integer(), nullable=False),
    sa.Column('data_aplicacao', sa.String(length=40), nullable=False),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cultura_gleba_id'], ['cultura_gleba.id'], ),
    sa.ForeignKeyConstraint(['produto_base_id'], ['produto_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colheita_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultura_gleba_id', sa.Integer(), nullable=False),
    sa.Column('data_colheita', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('qualidade', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cultura_gleba_id'], ['cultura_gleba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colheita_registro')
    op.drop_table('aplicacao_insumo')
    op.drop_table('cultura_gleba')
    op.drop_table('upload_arquivo')
    op.drop_table('ia_interacao')
    op.drop_table('gleba')
    op.drop_table('financeiro_lancamento')
    op.drop_table('equipe_membro')
    op.drop_table('cultura')
    op.drop_table('propriedade')
    op.drop_table('produto_tecnico')
    op.drop_table('produto_preco')
    op.drop_table('produto_imagem')
    op.drop_table('usuario')
    op.drop_table('produto_base')
    # ### end Alembic commands ###
