"""add usuario_propriedade senha_reset_token log_auditoria

Revision ID: e3e72eacc334
Revises: 97642b24c238
Create Date: 2026-06-29 20:12:44.705171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e72eacc334'
down_revision = '97642b24c238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('propriedade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senha_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('expira_em', sa.String(length=40), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('usado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('usuario_propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_propriedade')
    op.drop_table('senha_reset_token')
    op.drop_table('log_auditoria')
    # ### end Alembic commands ###
